name: CI
on: [push]
jobs: 
  general:
    name: Linting and Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Install packages
        run: npm ci

      - name: Run ESlint
        run: npm run lint